"use strict";
var name1 = "'Hey Marwa Nair,i have started learning TYPESCRIPT'";
console.log(name1);
var num1 = 55;
var num2 = 59;
var num3 = 53;
var num4 = 25;
var num5 = 89;
var num6 = 13;
var num7 = 10;
var num8 = 12;
var num9 = 18;
var num10 = 62;
var add = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log("Addition" + ' ' + add);
var subtraction = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log("subtraction" + ' ' + subtraction);
var multi = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log("multiplying" + ' ' + multi);
var division = num10 / num5;
console.log("division" + ' ' + division);
var pio = num2 + (num3 * num6) / num4 - num9;
console.log(pio);
